# Generated by Django 2.1.4 on 2019-03-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpFresher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EmpProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=40)),
            ],
        ),
    ]
